# Generated by Django 3.2.4 on 2021-08-27 13:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_showtime_seat_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='seat_taken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), default=list, size=None),
        ),
    ]
