# Generated by Django 3.2.4 on 2021-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_hero',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='image_normal',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
