# Generated by Django 3.2.4 on 2021-08-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_showtime_seat_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
