# Generated by Django 3.2.4 on 2021-08-24 00:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='seating_plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), default=list, size=None),
        ),
    ]
