# Generated by Django 3.2.4 on 2021-08-28 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210828_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='seat_taken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), default=list, null=True, size=None),
        ),
    ]
