# Generated by Django 3.2.4 on 2021-08-24 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_seating_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='seating',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), default=list, size=None),
        ),
    ]
